oss:
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  bucketName: other-file-manager
  rootPath: xiaohongshu/
  accessKey: ***
  accessValue: ***
  returnBaseUrl: http://other-file-manager.oss-cn-hangzhou.aliyuncs.com/

spring:
  servlet:
    multipart:
      max-file-size: 20MB   # 默认最大1M
      max-request-size: 20MB
